# Parameters for the Safety Checker
/**:
  ros__parameters:
    plane_offset: 0.5 # the polyhedra are expanded by this offset because the planner is constrained by the planes, but the controller is not perfectly accurate so to avoid landing, we add a little margin

    position_uncertainty_threshold: 0.2 # if the position variance along the vertical/horizontal coordinates is bigger than this value, we land

    # Defines safety boundary as a list of hyperplanes: [a, b, c, d]
    # for the equation ax + by + cz + d = 0
    # A point (x,y,z) is 'safe' if (a*x + b*y + c*z + d) <= 0 for ALL planes.
    #
    # Example: A 2x2x2m box centered at (0,0,1)
    planes: [
        # a,    b,    c,    d
         1.0,  0.0,  0.0, -2.8,  # x <= 1.0
        -1.0,  0.0,  0.0, -2.8,  # x >= -1.0
         0.0,  1.0,  0.0, -2.8,  # y <= 1.0
         0.0, -1.0,  0.0, -2.8,  # y >= -1.0
         0.0,  0.0,  1.0, -3.2,  # z <= 2.0
         0.0,  0.0, -1.0,  0.3   # z >= 0.3
      ]
      
