- name: Download Base ROS
  ansible.builtin.apt:
    name: 
      - ros-humble-ros-base
      - ros-dev-tools
      - ros-humble-mavros
      - ros-humble-mavros-extras
      - ros-humble-rosbag2-storage-mcap
      - ros-humble-domain-bridge
      - ros-humble-image-transport
      - ros-humble-compressed-image-transport
      - ros-humble-theora-image-transport
    update_cache: true
    state: latest
