/**:
  ros__parameters:
    # plugin_denylist:
    #   # common

    #   # extras
    #   - image_pub
    #   - vibration
    #   - distance_sensor
    #   - rangefinder
    #   - wheel_odometry

    plugin_allowlist:
      - sys_status
      - command
      - imu
      - rc_io
      - param
      - vision*
      - local*
      - global_position
      - home_position
      - setpoint_*
      - actuator_control


